version: "3.1"

services:
  # attach to the app w/ "docker attach `docker ps | grep noname1007_nessus | cut -d ' ' -f1`"
  nessus:
    container_name: noname1007_nessus
    image: noname1007/nessus:aarch64
    restart: always
    platform: linux/aarch64
    environment:
      - TZ=Asia/Ho_Chi_Minh
    # volumes:
    #   - ./nessus/:/opt/nessus/etc/nessus/
    ports:
      - "18834:8834"
    stdin_open: true
    tty: true
##docker exec -it noname1007_nessus /bin/bash /nessus/update.sh
##docker exec -it noname1007_nessus /opt/nessus/sbin/nessuscli chpasswd admin
##docker run -itd --name=noname1007_nessus -p 8834:8834 noname1007/nessus --platform=linux/amd64